#!/bin/bash
# PR Monitoring script for lifeform-2
# This script checks for new PRs since the last activation and queues them for review

# Load error utilities for consistent error handling
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$PROJECT_ROOT/core/system/error_utils.sh"

# Script name for logging
SCRIPT_NAME="pr_monitor.sh"

# State file to track last checked PR
PR_STATE_FILE="$PROJECT_ROOT/logs/pr_monitor_state.json"

# Ensure logs directory exists
mkdir -p "$PROJECT_ROOT/logs"

# Check if the gh CLI is installed and functioning
check_gh_cli() {
  if ! command -v gh &>/dev/null; then
    log_error "GitHub CLI (gh) is not installed or not in PATH" "$SCRIPT_NAME"
    echo "Please install the GitHub CLI from https://cli.github.com/"
    return 1
  fi
  
  # Check authentication status
  if ! gh auth status &>/dev/null; then
    log_warning "GitHub CLI is not authenticated with GitHub" "$SCRIPT_NAME"
    echo "Please run 'gh auth login' to authenticate with GitHub"
    return 1
  fi
  
  return 0
}

# Function to get the most recent PR number from the state file
get_last_checked_pr() {
  if [ -f "$PR_STATE_FILE" ]; then
    last_pr=$(jq -r '.last_checked_pr // 0' "$PR_STATE_FILE")
    log_info "Last checked PR: #$last_pr" "$SCRIPT_NAME"
    echo "$last_pr"
  else
    log_info "No state file found, creating new one" "$SCRIPT_NAME"
    echo '{"last_checked_pr": 0, "last_checked_time": "2025-03-06T00:00:00Z"}' > "$PR_STATE_FILE"
    echo "0"
  fi
}

# Function to update the state file with the latest PR number
update_last_checked_pr() {
  local pr_number="$1"
  
  if [ -z "$pr_number" ]; then
    log_error "PR number is required to update state" "$SCRIPT_NAME"
    return 1
  fi
  
  # Create or update the state file
  echo "{\"last_checked_pr\": $pr_number, \"last_checked_time\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > "$PR_STATE_FILE"
  log_info "Updated state file with last checked PR: #$pr_number" "$SCRIPT_NAME"
  
  return 0
}

# Function to check for new PRs
check_new_prs() {
  log_info "Checking for new PRs..." "$SCRIPT_NAME"
  
  if ! check_gh_cli; then
    return 1
  fi
  
  # Get the last checked PR number
  last_pr=$(get_last_checked_pr)
  
  # Get current list of open PRs, sorted by newest first
  log_info "Fetching current list of open PRs..." "$SCRIPT_NAME"
  pr_list=$(gh pr list --json number,title,createdAt,url --limit 10 --state open)
  
  # Validate JSON output
  if ! echo "$pr_list" | jq empty >/dev/null 2>&1; then
    log_error "Invalid JSON returned from GitHub CLI" "$SCRIPT_NAME"
    echo "[]"
    return 1
  fi
  
  # Check if PR list is empty
  if [ -z "$pr_list" ] || [ "$pr_list" = "[]" ]; then
    log_info "No open PRs found" "$SCRIPT_NAME"
    # Set highest PR to 0 if no PRs exist
    update_last_checked_pr "0"
    echo "[]"
    return 0
  fi
  
  # Get the highest PR number from the list
  highest_pr=$(echo "$pr_list" | jq -r 'map(.number) | max')
  
  # Validate highest_pr is a number
  if ! [[ "$highest_pr" =~ ^[0-9]+$ ]]; then
    log_error "Invalid highest PR number: $highest_pr" "$SCRIPT_NAME"
    echo "[]"
    return 1
  fi
  
  # Find all PRs that are newer than the last checked PR
  log_info "Looking for PRs newer than PR #$last_pr..." "$SCRIPT_NAME"
  new_prs=$(echo "$pr_list" | jq -c "[.[] | select(.number > $last_pr)]")
  
  # Validate new_prs JSON
  if ! echo "$new_prs" | jq empty >/dev/null 2>&1; then
    log_error "Invalid JSON generated for new PRs" "$SCRIPT_NAME"
    echo "[]"
    return 1
  fi
  
  new_pr_count=$(echo "$new_prs" | jq '. | length')
  
  # Validate new_pr_count is a number
  if ! [[ "$new_pr_count" =~ ^[0-9]+$ ]]; then
    log_error "Invalid new PR count: $new_pr_count" "$SCRIPT_NAME"
    echo "[]"
    return 1
  fi
  
  # Update state file with the highest PR number
  if [ -n "$highest_pr" ] && [ "$highest_pr" != "null" ]; then
    update_last_checked_pr "$highest_pr"
  fi
  
  # Log results
  if [ "$new_pr_count" -gt 0 ]; then
    log_info "Found $new_pr_count new PR(s) to review" "$SCRIPT_NAME"
  else
    log_info "No new PRs found since last check" "$SCRIPT_NAME"
  fi
  
  # Return the new PRs as a JSON array
  echo "$new_prs"
  
  return 0
}

# Function to queue PR reviews
queue_pr_reviews() {
  local new_prs="$1"
  
  if [ -z "$new_prs" ] || [ "$new_prs" = "[]" ]; then
    log_info "No PRs to queue for review" "$SCRIPT_NAME"
    return 0
  fi
  
  log_info "Queuing PRs for review..." "$SCRIPT_NAME"
  
  # Create a commands file for PR reviews if one doesn't exist
  local commands_file="$PROJECT_ROOT/pr_review_commands.sh"
  echo "#!/bin/bash" > "$commands_file"
  echo "# PR review commands generated on $(date)" >> "$commands_file"
  echo "# DO NOT EDIT - This file is automatically generated" >> "$commands_file"
  echo "" >> "$commands_file"
  
  # Get the number of PRs to review
  local pr_count=$(echo "$new_prs" | jq '. | length')
  
  # Validate pr_count is a number
  if ! [[ "$pr_count" =~ ^[0-9]+$ ]]; then
    log_error "Invalid PR count: $pr_count" "$SCRIPT_NAME"
    echo "# No new PRs to review - invalid count" >> "$commands_file"
    echo "echo \"No valid PRs found for review\"" >> "$commands_file"
    chmod +x "$commands_file"
    return 1
  fi
  
  if [ "$pr_count" -gt 0 ]; then
    echo "echo \"Starting review of $pr_count new PR(s)...\"" >> "$commands_file"
    echo "" >> "$commands_file"
    
    # Generate review commands for each PR
    for i in $(seq 0 $(($pr_count - 1))); do
      local pr_number=$(echo "$new_prs" | jq -r ".[$i].number")
      local pr_title=$(echo "$new_prs" | jq -r ".[$i].title")
      local pr_url=$(echo "$new_prs" | jq -r ".[$i].url")
      
      # Add PR review command to the file
      echo "echo \"Reviewing PR #$pr_number: $pr_title\"" >> "$commands_file"
      echo "echo \"URL: $pr_url\"" >> "$commands_file"
      echo "$PROJECT_ROOT/modules/communication/pr_review.sh review $pr_number" >> "$commands_file"
      echo "echo \"PR #$pr_number review completed\"" >> "$commands_file"
      echo "" >> "$commands_file"
    done
    
    echo "echo \"All PR reviews completed\"" >> "$commands_file"
  else
    # This is a fallback - should never happen since we check above
    echo "# No new PRs to review" >> "$commands_file"
    echo "echo \"No new PRs found for review\"" >> "$commands_file"
  fi
  
  # Make the file executable
  chmod +x "$commands_file"
  
  log_info "$pr_count PR(s) queued for review in $commands_file" "$SCRIPT_NAME"
  
  return 0
}

# Function to initiate PR monitoring
monitor_prs() {
  log_info "Starting PR monitoring..." "$SCRIPT_NAME"
  
  # Check for new PRs
  new_prs=$(check_new_prs)
  
  if [ $? -ne 0 ]; then
    log_error "Failed to check for new PRs" "$SCRIPT_NAME"
    return 1
  fi
  
  # Queue reviews for new PRs
  queue_pr_reviews "$new_prs"
  
  log_info "PR monitoring completed" "$SCRIPT_NAME"
  return 0
}

# Function to explain the PR monitoring workflow
explain_workflow() {
  echo "===== PR Monitoring Workflow ====="
  echo ""
  echo "The PR monitoring workflow follows these steps:"
  echo ""
  echo "1. Check for the last monitored PR number in state file"
  echo "2. Fetch current open PRs from GitHub"
  echo "3. Identify PRs that are newer than the last checked PR"
  echo "4. Update the state file with the latest PR number"
  echo "5. Queue the new PRs for review"
  echo "6. Generate review commands that will be executed during activation"
  echo ""
  echo "This workflow ensures that:"
  echo "- All new PRs are automatically detected"
  echo "- The state is maintained across activations"
  echo "- Each PR is reviewed only once"
  echo "- Reviews are performed without interrupting other operations"
  echo ""
  echo "For manual monitoring, you can use:"
  echo "  $0 monitor"
  echo ""
}

# Show help message
show_help() {
  echo "Usage: $0 COMMAND"
  echo ""
  echo "Commands:"
  echo "  monitor           - Check for new PRs and queue them for review"
  echo "  workflow          - Explain the PR monitoring workflow"
  echo "  help              - Show this help message"
  echo ""
  echo "Example:"
  echo "  $0 monitor"
}

# Main execution
case "$1" in
  "monitor")
    monitor_prs
    ;;
  "workflow")
    explain_workflow
    ;;
  "help"|"--help"|"-h")
    show_help
    ;;
  *)
    log_error "Unknown command: $1" "$SCRIPT_NAME"
    show_help
    exit 1
    ;;
esac

exit 0